name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  checks:
    name: 'Checks'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y nmap

      - name: Run tests
        run: |
          make docker-mock-vuln-server
          make test
